Fix docker setup

diff --git a/ver b/ver
--- a/ver
+++ b/ver
@@ -1,22 +1,28 @@
 #!/bin/bash
 
-# TODO check if needed
-# Source the ".env" file so Laravel's environment variables are available...
+VER_VERSION=1.3.0
+
 if [ -f ./.env ]; then
     source ./.env
 fi
 
 export APP_PORT=${APP_PORT:-80}
 export APP_SERVICE=${APP_SERVICE:-"app"}
-export DB_PORT=${DB_PORT:-3306}
-export HOST_UID=$(id -u)
+export HOST_UID
+export APP_SHORT_URL
+export DB_FORWARD_PORT=${DB_FORWARD_PORT:-3306}
+
+HOST_UID=$(id -u)
+
+# Remove http and https from APP_URL
+APP_SHORT_URL=$(echo "${APP_URL:-"localhost"}" | sed "s/https\?:\/\///")
 
 #######################################
 # FUNCTIONS
 #######################################
 
 dockerCompose () {
-    docker-compose -f docker-compose.yml -f docker-compose.dev.yml "${@:1}"
+    docker compose -f docker-compose.yml -f docker-compose.dev.yml "${@:1}"
 }
 
 # Run an Artisan command
@@ -63,7 +69,7 @@ restart () {
 
 # Start the containers
 start () {
-    dockerCompose up -d
+    dockerCompose up -d --remove-orphans
 }
 
 # Stop the containers
@@ -71,37 +77,68 @@ stop () {
     dockerCompose stop
 }
 
+exec () {
+    dockerCompose exec "${@:1}"
+}
+
 # Run a Yarn command
 yarn () {
     dockerCompose run --rm frontend yarn "${@:1}"
 }
 
-env () {
-    if [ ! -f .env ]; then
-        cp .env.example .env
-    fi
-}
+new () {
+    if [ -d "app" ]
+        then
+            echo "Laravel is already installed"
+            exit 1
+        fi
 
-makeProject () {
     docker run -u ${UID}:${UID} --rm -v $(pwd):/app -w /app composer composer create-project --prefer-dist laravel/laravel laravel-app
 
     shopt -s dotglob nullglob
 
     mv ./laravel-app/* .
     rm -rf laravel-app
+
+    sed -i 's/DB_HOST=127.0.0.1/DB_HOST=mysql/' .env .env.example
+    sed -i 's/DB_USERNAME=root/DB_USERNAME=db_user/' .env .env.example
+    sed -i 's/DB_PASSWORD=/DB_PASSWORD=db_secret/' .env .env.example
+
+    start
+
+    until curl localhost:"$DB_FORWARD_PORT" --http0.9 --output /dev/null --silent
+    do
+        {
+            echo 'Waiting for database to be ready...'
+            ((COUNT++)) && ((COUNT==20)) && echo "Could not connect to database after 20 tries!" && exit 1
+            sleep 3
+        } 1>&2
+    done
+
+    artisan migrate
+
+    composer require --dev barryvdh/laravel-ide-helper
+    artisan ide-helper:generate && artisan ide-helper:meta && artisan ide-helper:models --write-mixin
+    grep -qxF '_ide_helper*.php' .gitignore || echo '_ide_helper*.php' >> .gitignore
+    grep -qxF '.phpstorm.meta.php' .gitignore || echo '.phpstorm.meta.php' >> .gitignore
+
+    lintInstall
+    lint
+
+    git init && git add -A && git commit -m "Initial commit"
+
+    source .env && echo "$APP_URL"
 }
 
 hosts () {
     read -p "This command will add your app url to /etc/hosts. Are you sure? [y/n]: " -r
     if [[ ! $REPLY =~ ^[Yy]$ ]]; then exit; fi
 
-    app_url="$(cat .env | grep 'APP_URL' | cut -d '=' -f2)"
-
-    if [ -z "$app_url" ]
+    if [ -z "$APP_SHORT_URL" ]
     then
-          echo "APP_URL is empty. Aborting."
+          echo "APP_SHORT_URL is empty. Aborting."
     else
-          echo "127.0.0.1	$app_url" | sudo tee -a /etc/hosts
+          echo "127.0.0.1	$APP_SHORT_URL" | sudo tee -a /etc/hosts
           echo "Added to /etc/hosts"
     fi
 }
@@ -113,10 +150,16 @@ lint () {
         return
     fi
 
-    dockerCompose run --rm app php tools/php-cs-fixer/vendor/bin/php-cs-fixer fix "${@:1}"
+    dockerCompose run --rm app php tools/php-cs-fixer/vendor/bin/php-cs-fixer fix
 }
 
 lintInstall () {
+    if [ -d "tools/php-cs-fixer" ]
+    then
+        echo "php-cs-fixer already installed"
+        exit 1
+    fi
+
     echo "Installing vertex-it/php-cs"
 
     mkdir --parents tools/php-cs-fixer
@@ -125,6 +168,21 @@ lintInstall () {
     cp tools/php-cs-fixer/vendor/vertex-it/php-cs/src/.php-cs-fixer.dist.php .php-cs-fixer.dist.php
 
     echo "Done. Run \"ver lint\" to run cs fixer"
+
+    grep -qxF '/tools' .gitignore || echo '/tools' >> .gitignore
+    grep -qxF '.php-cs-fixer.*' .gitignore || echo '.php-cs-fixer.*' >> .gitignore
+}
+
+version () {
+    VER_SCRIPT_LOCATION="https://raw.githubusercontent.com/vertex-it/laravel-docker-setup/master/ver"
+
+    LATEST_VERSION=$(curl -s $VER_SCRIPT_LOCATION | grep -m 1 VER_VERSION | awk -F '=' '{print $2}')
+
+    if [ "$VER_VERSION" == "$LATEST_VERSION" ]; then
+        echo "ver script is up to date."
+    else
+        echo -e "ver script is out of date.\nCurrent version: $VER_VERSION - Latest version: $LATEST_VERSION"
+    fi
 }
 
 case "$1" in
@@ -158,6 +216,9 @@ case "$1" in
     shell)
         dockerCompose exec -u dkuser "$APP_SERVICE" sh
         ;;
+    exec)
+        exec "${@:2}"
+        ;;
     tinker)
         dockerCompose exec -u dkuser "$APP_SERVICE" php artisan tinker
         ;;
@@ -171,46 +232,49 @@ case "$1" in
         hosts
         ;;
     lint)
-        lint "${@:2}"
+        lint
         ;;
     lint-install)
         lintInstall
         ;;
-    init)
-        env \
-            && down -v \
-            && build \
-            && composer install \
-            && artisan key:generate --ansi \
-            && artisan migrate \
-            && start
+    new)
+        new
         ;;
-    make-project)
-        makeProject
+    init)
+        ./app-init.sh
+        ;;
+    version)
+        version
         ;;
     *)
         cat << EOF
 
-Command line interface for the Docker-based web development environment demo.
+Command line interface for the Docker-based web development environment ver.
 
 Usage:
-    demo <command> [options] [arguments]
+    ver <command> [options] [arguments]
 
 Available commands:
-    artisan ................................... Run an Artisan command
-    build [image] ............................. Build all of the images or the specified one
-    composer .................................. Run a Composer command
-    destroy ................................... Remove the entire Docker environment
-    down [-v] ................................. Stop and destroy all containers
-                                                Options:
-                                                    -v .................... Destroy the volumes as well
-    init ...................................... Initialise the Docker environment and the application
-    logs [container] .......................... Display and tail the logs of all containers or the specified one's
-    restart ................................... Restart the containers
-    start ..................................... Start the containers
-    stop ...................................... Stop the containers
-    update .................................... Update the Docker environment
-    yarn ...................................... Run a Yarn command
+    start|up ................................ Start the containers
+    stop|down ............................... Stop the containers
+    restart ................................. Restart the containers
+    build ................................... Build app image
+    destroy ................................. Remove the entire Docker environment
+    docker-compose .......................... Run docker-compose command
+    exec [container] [command] .............. Execute the command in the given container
+    logs [container] ........................ Display and tail the logs of all containers or the specified one's
+    composer ................................ Run a Composer command
+    art|artisan ............................. Run an Artisan command
+    shell ................................... Go to the app container's shell
+    tinker .................................. Run Tinker session
+    npm ..................................... Run the npm command
+    share ................................... Get the public tunnel URL of the project
+    hosts ................................... Add local app URL to the /etc/hosts file
+    lint .................................... Run PHP CS Fixer
+    lint-install ............................ Install PHP CS Fixer
+    new ..................................... Install and start new Laravel application
+    init .................................... Initialize and start existing Laravel application
+    version ................................. Check ver script version
 
 EOF
         exit 1
